//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FieldService.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string AddCallPage_Books {
            get {
                return ResourceManager.GetString("AddCallPage_Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brochures.
        /// </summary>
        public static string AddCallPage_Brochures {
            get {
                return ResourceManager.GetString("AddCallPage_Brochures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Saved..
        /// </summary>
        public static string AddCallPage_CallSaved {
            get {
                return ResourceManager.GetString("AddCallPage_CallSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Saving Failed..
        /// </summary>
        public static string AddCallPage_CallSavedFailed {
            get {
                return ResourceManager.GetString("AddCallPage_CallSavedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        public static string AddCallPage_Date {
            get {
                return ResourceManager.GetString("AddCallPage_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete call.
        /// </summary>
        public static string AddCallPage_DeleteCall {
            get {
                return ResourceManager.GetString("AddCallPage_DeleteCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this call?.
        /// </summary>
        public static string AddCallPage_DeleteCallConfirmation {
            get {
                return ResourceManager.GetString("AddCallPage_DeleteCallConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the call failed..
        /// </summary>
        public static string AddCallPage_DeleteCallFailed {
            get {
                return ResourceManager.GetString("AddCallPage_DeleteCallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to call.
        /// </summary>
        public static string AddCallPage_Headline {
            get {
                return ResourceManager.GetString("AddCallPage_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazines.
        /// </summary>
        public static string AddCallPage_Magazines {
            get {
                return ResourceManager.GetString("AddCallPage_Magazines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTES.
        /// </summary>
        public static string AddCallPage_Notes {
            get {
                return ResourceManager.GetString("AddCallPage_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLACEMENTS.
        /// </summary>
        public static string AddCallPage_Placements {
            get {
                return ResourceManager.GetString("AddCallPage_Placements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string AddCallPage_Save {
            get {
                return ResourceManager.GetString("AddCallPage_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must save the RV before adding a call..
        /// </summary>
        public static string AddCallPage_SaveBeforeEditMessage {
            get {
                return ResourceManager.GetString("AddCallPage_SaveBeforeEditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auxiliary Hour(s) Saved..
        /// </summary>
        public static string AddRBCTimePage_Confirmation {
            get {
                return ResourceManager.GetString("AddRBCTimePage_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to convert to time.
        /// </summary>
        public static string AddRBCTimePage_ConvertMenuItem {
            get {
                return ResourceManager.GetString("AddRBCTimePage_ConvertMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        public static string AddRBCTimePage_Date {
            get {
                return ResourceManager.GetString("AddRBCTimePage_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string AddRBCTimePage_Delete {
            get {
                return ResourceManager.GetString("AddRBCTimePage_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auxiliary time.
        /// </summary>
        public static string AddRBCTimePage_Headline {
            get {
                return ResourceManager.GetString("AddRBCTimePage_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auxiliary time is any type of time that is not field service related, but that can be reported on your field service report - e.g. for some appointed brothers &amp; sisters time spent at regional building committee sites building kingdom halls can be noted on their report.  Please see your congregation service overseer for details..
        /// </summary>
        public static string AddRBCTimePage_Note {
            get {
                return ResourceManager.GetString("AddRBCTimePage_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTES.
        /// </summary>
        public static string AddRBCTimePage_Notes {
            get {
                return ResourceManager.GetString("AddRBCTimePage_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string AddRBCTimePage_Save {
            get {
                return ResourceManager.GetString("AddRBCTimePage_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIME.
        /// </summary>
        public static string AddRBCTimePage_Time {
            get {
                return ResourceManager.GetString("AddRBCTimePage_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bible Studies.
        /// </summary>
        public static string AddTime_BibleStudies {
            get {
                return ResourceManager.GetString("AddTime_BibleStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string AddTimePage_Books {
            get {
                return ResourceManager.GetString("AddTimePage_Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brochures.
        /// </summary>
        public static string AddTimePage_Brochures {
            get {
                return ResourceManager.GetString("AddTimePage_Brochures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to convert to rbc time.
        /// </summary>
        public static string AddTimePage_ConvertMenuItem {
            get {
                return ResourceManager.GetString("AddTimePage_ConvertMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        public static string AddTimePage_Date {
            get {
                return ResourceManager.GetString("AddTimePage_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string AddTimePage_DeleteMenuItem {
            get {
                return ResourceManager.GetString("AddTimePage_DeleteMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        public static string AddTimePage_Headline {
            get {
                return ResourceManager.GetString("AddTimePage_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazines.
        /// </summary>
        public static string AddTimePage_Magazines {
            get {
                return ResourceManager.GetString("AddTimePage_Magazines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Failed..
        /// </summary>
        public static string AddTimePage_Messages_RBCConvertFailed {
            get {
                return ResourceManager.GetString("AddTimePage_Messages_RBCConvertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Converted to RBC..
        /// </summary>
        public static string AddTimePage_Messages_RBCConvertSuccess {
            get {
                return ResourceManager.GetString("AddTimePage_Messages_RBCConvertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: {0} Hours Saved..
        /// </summary>
        public static string AddTimePage_Messages_SaveCompleted {
            get {
                return ResourceManager.GetString("AddTimePage_Messages_SaveCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Save Time..
        /// </summary>
        public static string AddTimePage_Messages_SaveFailed {
            get {
                return ResourceManager.GetString("AddTimePage_Messages_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Failed..
        /// </summary>
        public static string AddTimePage_Messages_TimeDeleteFailed {
            get {
                return ResourceManager.GetString("AddTimePage_Messages_TimeDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Deleted..
        /// </summary>
        public static string AddTimePage_Messages_TimeDeleteSuccess {
            get {
                return ResourceManager.GetString("AddTimePage_Messages_TimeDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTES.
        /// </summary>
        public static string AddTimePage_Notes {
            get {
                return ResourceManager.GetString("AddTimePage_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLACEMENTS.
        /// </summary>
        public static string AddTimePage_Placements {
            get {
                return ResourceManager.GetString("AddTimePage_Placements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Visits.
        /// </summary>
        public static string AddTimePage_RVs {
            get {
                return ResourceManager.GetString("AddTimePage_RVs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string AddTimePage_Save {
            get {
                return ResourceManager.GetString("AddTimePage_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIME.
        /// </summary>
        public static string AddTimePage_Time {
            get {
                return ResourceManager.GetString("AddTimePage_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://wol.jw.org/en/wol/dt/r1/lp-e/{0}/{1}/{2}.
        /// </summary>
        public static string Application_DailyTextURL {
            get {
                return ResourceManager.GetString("Application_DailyTextURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIELD SERVICE.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string BackupAndRestorePage_Backup {
            get {
                return ResourceManager.GetString("BackupAndRestorePage_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage cloud.
        /// </summary>
        public static string BackupAndRestorePage_Headline {
            get {
                return ResourceManager.GetString("BackupAndRestorePage_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Backup Date.
        /// </summary>
        public static string BackupAndRestorePage_LastBackup {
            get {
                return ResourceManager.GetString("BackupAndRestorePage_LastBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign-in and allow access to your SkyDrive..
        /// </summary>
        public static string BackupAndRestorePage_Message {
            get {
                return ResourceManager.GetString("BackupAndRestorePage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0,0} of {1:0,0} downloaded..
        /// </summary>
        public static string BackupAndRestorePage_Messages_DwnlProgress {
            get {
                return ResourceManager.GetString("BackupAndRestorePage_Messages_DwnlProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never Backed Up!.
        /// </summary>
        public static string BackupAndRestorePage_Messages_NeverBackedUp {
            get {
                return ResourceManager.GetString("BackupAndRestorePage_Messages_NeverBackedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0,0} of {1:0,0} uploaded..
        /// </summary>
        public static string BackupAndRestorePage_Messages_Progress {
            get {
                return ResourceManager.GetString("BackupAndRestorePage_Messages_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Failed!.
        /// </summary>
        public static string BackupAndRestorePage_Messages_RestoreFailed {
            get {
                return ResourceManager.GetString("BackupAndRestorePage_Messages_RestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Completed!.
        /// </summary>
        public static string BackupAndRestorePage_Messages_RestoreSuccess {
            get {
                return ResourceManager.GetString("BackupAndRestorePage_Messages_RestoreSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring Now....
        /// </summary>
        public static string BackupAndRestorePage_Messages_Restoring {
            get {
                return ResourceManager.GetString("BackupAndRestorePage_Messages_Restoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skydrive Listing Failed..
        /// </summary>
        public static string BackupAndRestorePage_Messages_SkyDriveListingFailed {
            get {
                return ResourceManager.GetString("BackupAndRestorePage_Messages_SkyDriveListingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t upload your backup data. Please log out and try again..
        /// </summary>
        public static string BackupAndRestorePage_Messages_UploadFailed {
            get {
                return ResourceManager.GetString("BackupAndRestorePage_Messages_UploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0} {1}.
        /// </summary>
        public static string BackupAndRestorePage_Messages_Welcome {
            get {
                return ResourceManager.GetString("BackupAndRestorePage_Messages_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not signed in..
        /// </summary>
        public static string BackupAndRestorePage_NotSignedIn {
            get {
                return ResourceManager.GetString("BackupAndRestorePage_NotSignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string BackupAndRestorePage_Restore {
            get {
                return ResourceManager.GetString("BackupAndRestorePage_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string BackupAndRestorePage_SignIn {
            get {
                return ResourceManager.GetString("BackupAndRestorePage_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string BackupAndRestorePage_Signout {
            get {
                return ResourceManager.GetString("BackupAndRestorePage_Signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string BackupAndRestorePage_Welcome {
            get {
                return ResourceManager.GetString("BackupAndRestorePage_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return vists.
        /// </summary>
        public static string FullRVListPage_Headline {
            get {
                return ResourceManager.GetString("FullRVListPage_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Old.
        /// </summary>
        public static string FullRVListPage_YearOld {
            get {
                return ResourceManager.GetString("FullRVListPage_YearOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Service.
        /// </summary>
        public static string MainPage_AppName {
            get {
                return ResourceManager.GetString("MainPage_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE ABOVE IS COPYRIGHT 2012 WATCHTOWER BIBLE AND TRACT SOCIETY OF PENNSYLVANIA, INC. ALL RIGHTS RESERVED..
        /// </summary>
        public static string MainPage_DT_Copyright {
            get {
                return ResourceManager.GetString("MainPage_DT_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be connected to the internet to view the daily text..
        /// </summary>
        public static string MainPage_DT_ErrorText {
            get {
                return ResourceManager.GetString("MainPage_DT_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daily text.
        /// </summary>
        public static string MainPage_DT_Headline {
            get {
                return ResourceManager.GetString("MainPage_DT_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add auxiliary time.
        /// </summary>
        public static string MainPage_MainMenu_AddAuxTime {
            get {
                return ResourceManager.GetString("MainPage_MainMenu_AddAuxTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add return visit.
        /// </summary>
        public static string MainPage_MainMenu_AddRv {
            get {
                return ResourceManager.GetString("MainPage_MainMenu_AddRv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add time.
        /// </summary>
        public static string MainPage_MainMenu_AddTime {
            get {
                return ResourceManager.GetString("MainPage_MainMenu_AddTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backup &amp; restore.
        /// </summary>
        public static string MainPage_MainMenu_BackupRestore {
            get {
                return ResourceManager.GetString("MainPage_MainMenu_BackupRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} report.
        /// </summary>
        public static string MainPage_MainMenu_MonthReport {
            get {
                return ResourceManager.GetString("MainPage_MainMenu_MonthReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send service report.
        /// </summary>
        public static string MainPage_MainMenu_SendReport {
            get {
                return ResourceManager.GetString("MainPage_MainMenu_SendReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service year report.
        /// </summary>
        public static string MainPage_MainMenu_ServiceYearReport {
            get {
                return ResourceManager.GetString("MainPage_MainMenu_ServiceYearReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string MainPage_MainMenu_Settings {
            get {
                return ResourceManager.GetString("MainPage_MainMenu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to watchtower library.
        /// </summary>
        public static string MainPage_MainMenu_WtLib {
            get {
                return ResourceManager.GetString("MainPage_MainMenu_WtLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time ({0} hrs &amp; {1} min) added..
        /// </summary>
        public static string MainPage_Messages_AddedTime {
            get {
                return ResourceManager.GetString("MainPage_Messages_AddedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t add zero minutes..
        /// </summary>
        public static string MainPage_Messages_CantAddZeroMin {
            get {
                return ResourceManager.GetString("MainPage_Messages_CantAddZeroMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can donate in settings&gt;about later..
        /// </summary>
        public static string MainPage_Messages_DonateLater {
            get {
                return ResourceManager.GetString("MainPage_Messages_DonateLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is free to use. Submitting apps to the WP app store isn&apos;t. Would you consider a donation?.
        /// </summary>
        public static string MainPage_Messages_DonatePlease {
            get {
                return ResourceManager.GetString("MainPage_Messages_DonatePlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Hours: \t{0:0.0}\n.
        /// </summary>
        public static string MainPage_Report_AuxHours {
            get {
                return ResourceManager.GetString("MainPage_Report_AuxHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bible Studies:\t{0}.
        /// </summary>
        public static string MainPage_Report_BibleStudies {
            get {
                return ResourceManager.GetString("MainPage_Report_BibleStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books:\t\t{0}\n.
        /// </summary>
        public static string MainPage_Report_Books {
            get {
                return ResourceManager.GetString("MainPage_Report_Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brochures:\t{0}\n.
        /// </summary>
        public static string MainPage_Report_Brochures {
            get {
                return ResourceManager.GetString("MainPage_Report_Brochures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is my field service report for {0:MMMM}, {0:yyyy}:\n\n.
        /// </summary>
        public static string MainPage_Report_Header {
            get {
                return ResourceManager.GetString("MainPage_Report_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours:\t\t{0:0.00}\n.
        /// </summary>
        public static string MainPage_Report_Hours {
            get {
                return ResourceManager.GetString("MainPage_Report_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazines:\t{0}\n.
        /// </summary>
        public static string MainPage_Report_Mags {
            get {
                return ResourceManager.GetString("MainPage_Report_Mags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Visits:\t{0}\n.
        /// </summary>
        public static string MainPage_Report_RVs {
            get {
                return ResourceManager.GetString("MainPage_Report_RVs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day(s) Since Last Visit.
        /// </summary>
        public static string MainPage_RV_DaysSince {
            get {
                return ResourceManager.GetString("MainPage_RV_DaysSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return visits.
        /// </summary>
        public static string MainPage_RvHeadline {
            get {
                return ResourceManager.GetString("MainPage_RvHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bible Studies.
        /// </summary>
        public static string MainPage_Time_BibleStudies {
            get {
                return ResourceManager.GetString("MainPage_Time_BibleStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string MainPage_Time_Books {
            get {
                return ResourceManager.GetString("MainPage_Time_Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brochures.
        /// </summary>
        public static string MainPage_Time_Brochures {
            get {
                return ResourceManager.GetString("MainPage_Time_Brochures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        public static string MainPage_Time_Headline {
            get {
                return ResourceManager.GetString("MainPage_Time_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazines.
        /// </summary>
        public static string MainPage_Time_Magazines {
            get {
                return ResourceManager.GetString("MainPage_Time_Magazines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string MainPage_Time_Notes {
            get {
                return ResourceManager.GetString("MainPage_Time_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Visits.
        /// </summary>
        public static string MainPage_Time_ReturnVisits {
            get {
                return ResourceManager.GetString("MainPage_Time_ReturnVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Bible Studies.
        /// </summary>
        public static string ReportingPage_BibleStudies_1 {
            get {
                return ResourceManager.GetString("ReportingPage_BibleStudies_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entries.
        /// </summary>
        public static string ReportingPage_Entries {
            get {
                return ResourceManager.GetString("ReportingPage_Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entries.
        /// </summary>
        public static string ReportingPage_Entries_Header {
            get {
                return ResourceManager.GetString("ReportingPage_Entries_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Books, .
        /// </summary>
        public static string ReportingPage_Report_Books {
            get {
                return ResourceManager.GetString("ReportingPage_Report_Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Brochures.
        /// </summary>
        public static string ReportingPage_Report_Brochures {
            get {
                return ResourceManager.GetString("ReportingPage_Report_Brochures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time In Hours.
        /// </summary>
        public static string ReportingPage_Report_ChartTitle {
            get {
                return ResourceManager.GetString("ReportingPage_Report_ChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  day(s).
        /// </summary>
        public static string ReportingPage_Report_Days {
            get {
                return ResourceManager.GetString("ReportingPage_Report_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: Service Year Begins in September..
        /// </summary>
        public static string ReportingPage_Report_Disclaimer {
            get {
                return ResourceManager.GetString("ReportingPage_Report_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FROM: {0}.
        /// </summary>
        public static string ReportingPage_Report_From {
            get {
                return ResourceManager.GetString("ReportingPage_Report_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report.
        /// </summary>
        public static string ReportingPage_Report_Headline {
            get {
                return ResourceManager.GetString("ReportingPage_Report_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Hour(s) on {1} Days.
        /// </summary>
        public static string ReportingPage_Report_HoursOnDays {
            get {
                return ResourceManager.GetString("ReportingPage_Report_HoursOnDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to legend.
        /// </summary>
        public static string ReportingPage_Report_Legend {
            get {
                return ResourceManager.GetString("ReportingPage_Report_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Magazines, .
        /// </summary>
        public static string ReportingPage_Report_Magazines {
            get {
                return ResourceManager.GetString("ReportingPage_Report_Magazines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my activity.
        /// </summary>
        public static string ReportingPage_Report_MyActivity {
            get {
                return ResourceManager.GetString("ReportingPage_Report_MyActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  on .
        /// </summary>
        public static string ReportingPage_Report_On {
            get {
                return ResourceManager.GetString("ReportingPage_Report_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTHER ACTIVITY.
        /// </summary>
        public static string ReportingPage_Report_OtherActivity {
            get {
                return ResourceManager.GetString("ReportingPage_Report_OtherActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLACEMENTS.
        /// </summary>
        public static string ReportingPage_Report_Placements {
            get {
                return ResourceManager.GetString("ReportingPage_Report_Placements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIME.
        /// </summary>
        public static string ReportingPage_Report_Time {
            get {
                return ResourceManager.GetString("ReportingPage_Report_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time in Hours.
        /// </summary>
        public static string ReportingPage_Report_TimeInHrs {
            get {
                return ResourceManager.GetString("ReportingPage_Report_TimeInHrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO: {0}.
        /// </summary>
        public static string ReportingPage_Report_To {
            get {
                return ResourceManager.GetString("ReportingPage_Report_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL: {0} Hour(s) and {1} Minute(s).
        /// </summary>
        public static string ReportingPage_Report_TotalHours {
            get {
                return ResourceManager.GetString("ReportingPage_Report_TotalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Return Visits.
        /// </summary>
        public static string ReportingPage_ReturnVisits_1 {
            get {
                return ResourceManager.GetString("ReportingPage_ReturnVisits_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share....
        /// </summary>
        public static string ReportingPage_Share {
            get {
                return ResourceManager.GetString("ReportingPage_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        public static string RVPage_Address_Address1 {
            get {
                return ResourceManager.GetString("RVPage_Address_Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        public static string RVPage_Address_Address2 {
            get {
                return ResourceManager.GetString("RVPage_Address_Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string RVPage_Address_City {
            get {
                return ResourceManager.GetString("RVPage_Address_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string RVPage_Address_Country {
            get {
                return ResourceManager.GetString("RVPage_Address_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Address: .
        /// </summary>
        public static string RVPage_Address_CurrentAddress {
            get {
                return ResourceManager.GetString("RVPage_Address_CurrentAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address.
        /// </summary>
        public static string RVPage_Address_Headline {
            get {
                return ResourceManager.GetString("RVPage_Address_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Notes.
        /// </summary>
        public static string RVPage_Address_LocationNotes {
            get {
                return ResourceManager.GetString("RVPage_Address_LocationNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string RVPage_Address_PostalCode {
            get {
                return ResourceManager.GetString("RVPage_Address_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Province/District.
        /// </summary>
        public static string RVPage_Address_StateDistrict {
            get {
                return ResourceManager.GetString("RVPage_Address_StateDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string RVPage_Address_Use {
            get {
                return ResourceManager.GetString("RVPage_Address_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD OR MODIFY RETURN VISIT.
        /// </summary>
        public static string RVPage_Headline {
            get {
                return ResourceManager.GetString("RVPage_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDRESS.
        /// </summary>
        public static string RVPage_Info_Address {
            get {
                return ResourceManager.GetString("RVPage_Info_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info.
        /// </summary>
        public static string RVPage_Info_Headline {
            get {
                return ResourceManager.GetString("RVPage_Info_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERSONAL INFO.
        /// </summary>
        public static string RVPage_Info_PersonalInfo {
            get {
                return ResourceManager.GetString("RVPage_Info_PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add visit.
        /// </summary>
        public static string RVPage_Menu_AddVisit {
            get {
                return ResourceManager.GetString("RVPage_Menu_AddVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete return visit.
        /// </summary>
        public static string RVPage_Menu_Delete {
            get {
                return ResourceManager.GetString("RVPage_Menu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email return visit.
        /// </summary>
        public static string RVPage_Menu_Email {
            get {
                return ResourceManager.GetString("RVPage_Menu_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export to contact record.
        /// </summary>
        public static string RVPage_Menu_Export {
            get {
                return ResourceManager.GetString("RVPage_Menu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset.
        /// </summary>
        public static string RVPage_Menu_Reset {
            get {
                return ResourceManager.GetString("RVPage_Menu_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string RVPage_Menu_Save {
            get {
                return ResourceManager.GetString("RVPage_Menu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the return visit?.
        /// </summary>
        public static string RVPage_Messages_Delete {
            get {
                return ResourceManager.GetString("RVPage_Messages_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to include all visits?.
        /// </summary>
        public static string RVPage_Messages_IncludeAllVisits {
            get {
                return ResourceManager.GetString("RVPage_Messages_IncludeAllVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include All Visits?.
        /// </summary>
        public static string RVPage_Messages_IncludeAllVisits2 {
            get {
                return ResourceManager.GetString("RVPage_Messages_IncludeAllVisits2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Visit Saved..
        /// </summary>
        public static string RVPage_Messages_Saved {
            get {
                return ResourceManager.GetString("RVPage_Messages_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string RVPage_Personal_Age {
            get {
                return ResourceManager.GetString("RVPage_Personal_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string RVPage_Personal_Description {
            get {
                return ResourceManager.GetString("RVPage_Personal_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string RVPage_Personal_FullName {
            get {
                return ResourceManager.GetString("RVPage_Personal_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to personal.
        /// </summary>
        public static string RVPage_Personal_Headline {
            get {
                return ResourceManager.GetString("RVPage_Personal_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string RVPage_Personal_PhoneNumber {
            get {
                return ResourceManager.GetString("RVPage_Personal_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Reminder.
        /// </summary>
        public static string RVPage_Reminders_AddReminder {
            get {
                return ResourceManager.GetString("RVPage_Reminders_AddReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reminders.
        /// </summary>
        public static string RVPage_Reminders_Headline {
            get {
                return ResourceManager.GetString("RVPage_Reminders_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string RVPage_Reminders_Notes {
            get {
                return ResourceManager.GetString("RVPage_Reminders_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date.
        /// </summary>
        public static string RVPage_Reminders_SelectDate {
            get {
                return ResourceManager.GetString("RVPage_Reminders_SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Time.
        /// </summary>
        public static string RVPage_Reminders_SelectTime {
            get {
                return ResourceManager.GetString("RVPage_Reminders_SelectTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  day(s) since visit.
        /// </summary>
        public static string RVPage_Visits_DaysSince {
            get {
                return ResourceManager.GetString("RVPage_Visits_DaysSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visits.
        /// </summary>
        public static string RVPage_Visits_Headline {
            get {
                return ResourceManager.GetString("RVPage_Visits_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Version: .
        /// </summary>
        public static string SettingsPage_About_AppVersion {
            get {
                return ResourceManager.GetString("SettingsPage_About_AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2013 Square.HipToBe.
        /// </summary>
        public static string SettingsPage_About_Copyright {
            get {
                return ResourceManager.GetString("SettingsPage_About_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Version: .
        /// </summary>
        public static string SettingsPage_About_CoreVersion {
            get {
                return ResourceManager.GetString("SettingsPage_About_CoreVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate To Development.
        /// </summary>
        public static string SettingsPage_About_Donate {
            get {
                return ResourceManager.GetString("SettingsPage_About_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string SettingsPage_About_Headline {
            get {
                return ResourceManager.GetString("SettingsPage_About_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help!.
        /// </summary>
        public static string SettingsPage_About_Help {
            get {
                return ResourceManager.GetString("SettingsPage_About_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINKS.
        /// </summary>
        public static string SettingsPage_About_Links {
            get {
                return ResourceManager.GetString("SettingsPage_About_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPEN SOURCE.
        /// </summary>
        public static string SettingsPage_About_OpenSource {
            get {
                return ResourceManager.GetString("SettingsPage_About_OpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this app!.
        /// </summary>
        public static string SettingsPage_About_Rate {
            get {
                return ResourceManager.GetString("SettingsPage_About_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Issue.
        /// </summary>
        public static string SettingsPage_About_ReportIssue {
            get {
                return ResourceManager.GetString("SettingsPage_About_ReportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is open source!.
        /// </summary>
        public static string SettingsPage_About_ThisAppFOSS {
            get {
                return ResourceManager.GetString("SettingsPage_About_ThisAppFOSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string SettingsPage_About_Version {
            get {
                return ResourceManager.GetString("SettingsPage_About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERSION.
        /// </summary>
        public static string SettingsPage_Settings_AddCallPlacements {
            get {
                return ResourceManager.GetString("SettingsPage_Settings_AddCallPlacements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string SettingsPage_Settings_AppSettings {
            get {
                return ResourceManager.GetString("SettingsPage_Settings_AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beautify Phone Numbers (US Only).
        /// </summary>
        public static string SettingsPage_Settings_BeautifyPhoneNumbers {
            get {
                return ResourceManager.GetString("SettingsPage_Settings_BeautifyPhoneNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congregation Service Overseer.
        /// </summary>
        public static string SettingsPage_Settings_CSO {
            get {
                return ResourceManager.GetString("SettingsPage_Settings_CSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the button above to choose the contact record of your CSO..
        /// </summary>
        public static string SettingsPage_Settings_CSO_Message1 {
            get {
                return ResourceManager.GetString("SettingsPage_Settings_CSO_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Age.
        /// </summary>
        public static string SettingsPage_Settings_DefaultAge {
            get {
                return ResourceManager.GetString("SettingsPage_Settings_DefaultAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Calls and RV.
        /// </summary>
        public static string SettingsPage_Settings_DeleteCallsAndRv {
            get {
                return ResourceManager.GetString("SettingsPage_Settings_DeleteCallsAndRv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: Deleting the calls will delete the RVs from your service report..
        /// </summary>
        public static string SettingsPage_Settings_DeleteCallsRvNote {
            get {
                return ResourceManager.GetString("SettingsPage_Settings_DeleteCallsRvNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string SettingsPage_Settings_Email {
            get {
                return ResourceManager.GetString("SettingsPage_Settings_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsPage_Settings_Headline {
            get {
                return ResourceManager.GetString("SettingsPage_Settings_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick Name.
        /// </summary>
        public static string SettingsPage_Settings_NickName {
            get {
                return ResourceManager.GetString("SettingsPage_Settings_NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Settings.
        /// </summary>
        public static string SettingsPage_Settings_PersonalSettings {
            get {
                return ResourceManager.GetString("SettingsPage_Settings_PersonalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set to ‘on’ placements recorded on a return visit call will count towards your monthly report. If you set this to ‘off’ you wil have to enter your placements twice (on the call and on the add time screen)..
        /// </summary>
        public static string SettingsPage_Settings_PlacementsMessage1 {
            get {
                return ResourceManager.GetString("SettingsPage_Settings_PlacementsMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy: This app uses location services to find your address when entering a new return visit. While the address you enter is stored, the GPS location data recorded while searching for an address is never stored or transmitted..
        /// </summary>
        public static string SettingsPage_Settings_PrivacyPolicy {
            get {
                return ResourceManager.GetString("SettingsPage_Settings_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round Time (15 Minute Increments).
        /// </summary>
        public static string SettingsPage_Settings_RoundTime {
            get {
                return ResourceManager.GetString("SettingsPage_Settings_RoundTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Send Method.
        /// </summary>
        public static string SettingsPage_Settings_SendMethod {
            get {
                return ResourceManager.GetString("SettingsPage_Settings_SendMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHARING OPTIONS.
        /// </summary>
        public static string SettingsPage_Settings_SharingOptions {
            get {
                return ResourceManager.GetString("SettingsPage_Settings_SharingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Field Service Signature.
        /// </summary>
        public static string SettingsPage_Settings_SignatureMessage {
            get {
                return ResourceManager.GetString("SettingsPage_Settings_SignatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature is only included on emailed reports. It’s left off of SMS reports..
        /// </summary>
        public static string SettingsPage_Settings_SignatureMessage2 {
            get {
                return ResourceManager.GetString("SettingsPage_Settings_SignatureMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        public static string SettingsPage_Settings_SMS {
            get {
                return ResourceManager.GetString("SettingsPage_Settings_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Location Services.
        /// </summary>
        public static string SettingsPage_Settings_UseLocServices {
            get {
                return ResourceManager.GetString("SettingsPage_Settings_UseLocServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL: {0} Hour(s) and {1} Minute(s) Auxiliary Time.
        /// </summary>
        public static string TimeReport_AuxHoursAndMinutes {
            get {
                return ResourceManager.GetString("TimeReport_AuxHoursAndMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Hour(s) &amp; {1} Minutes.
        /// </summary>
        public static string TimeReport_HoursAndMinutes {
            get {
                return ResourceManager.GetString("TimeReport_HoursAndMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Books.
        /// </summary>
        public static string ViewPreviousVisitPage_Books {
            get {
                return ResourceManager.GetString("ViewPreviousVisitPage_Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Brochures.
        /// </summary>
        public static string ViewPreviousVisitPage_Brochures {
            get {
                return ResourceManager.GetString("ViewPreviousVisitPage_Brochures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Magazines.
        /// </summary>
        public static string ViewPreviousVisitPage_Magazines {
            get {
                return ResourceManager.GetString("ViewPreviousVisitPage_Magazines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string ViewPreviousVisitPage_Menu_Edit {
            get {
                return ResourceManager.GetString("ViewPreviousVisitPage_Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTES.
        /// </summary>
        public static string ViewPreviousVisitPage_Notes {
            get {
                return ResourceManager.GetString("ViewPreviousVisitPage_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLACEMENTS.
        /// </summary>
        public static string ViewPreviousVisitPage_Placements {
            get {
                return ResourceManager.GetString("ViewPreviousVisitPage_Placements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETURN VISIT.
        /// </summary>
        public static string ViewPreviousVisitPage_Rv {
            get {
                return ResourceManager.GetString("ViewPreviousVisitPage_Rv", resourceCulture);
            }
        }
    }
}
